export const ROOT_ID =
  'chrome-extension-boilerplate-react-vite-content-view-root';

export const trainStations = [
  'Seoul',
  'Yongsan',
  'Yeongdeungpo',
  'Gwangmyeong',
  'Suwon',
  'Pyeongtaek',
  'CheonanAsan',
  'Cheonan',
  'Jochiwon',
  'Daejeon',
  'Seodaejeon',
  'Gimcheon',
  'Gumi',
  'Gimcheon Gumi',
  'Daegu',
  'Dongdaegu',
  'Pohang',
  'Miryang',
  'Gupo',
  'Busan',
  'Singyeongju',
  'Taehwagang',
  'Ulsan',
  'Haman',
  'Osong',
  'Masan',
  'ChangwonJungang',
  'Gyeongsan',
  'Nonsan',
  'Iksan',
  'Jeongeup',
  'Gwangju-Songjeong',
  'Mokpo',
  'Jeonju',
  'Suncheon',
  'Yeosu-Expo',
  'Daecheon',
  'Cheongnyangni',
  'Jecheon',
  'Donghae',
  'Gangneung',
  'Haengsin',
  'Chuncheon',
  'Namchuncheon',
  'Bujeon',
  'Sintanjin',
  'Yeongdong',
  'Waegwan',
  'Wonju',
  'Jeongdongjin',
  'Hongseong',
].sort();

export const trainStationsOptions = trainStations.map((station) => ({
  key: station,
  value: station,
}));

export const KORAIL_ROUTES = {
  root: '',
  form: 'EbizbfForeign_pr16100.do',
  search: 'EbizBfBookingTrainSearch.do',
  passenger: 'EbizBfPassengerInformation.do',
  payment: 'EbizBfTicketReservation.do',
  popup: 'popupView.do',
};

export const COUNTRIES = {
  '00': '',
  AR: 'ARGENTINA',
  AU: 'AUSTRALIA',
  AT: 'AUSTRIA',
  AF: 'Afghanistan',
  AB: 'Albania',
  AG: 'Algeria',
  AN: 'Angola',
  AM: 'Armenia',
  AZ: 'Azerbaijan',
  BH: 'BAHRAIN',
  BD: 'BANGLADESH',
  BE: 'BELGIUM',
  BO: 'BOLIVIA',
  BW: 'BOTSWANA',
  BR: 'BRAZIL',
  BG: 'BULGARIA',
  BM: 'Bahamas',
  BS: 'Barbados',
  BU: 'Belarus',
  BZ: 'Belize',
  BN: 'Benin',
  BT: 'Bhutan',
  BB: 'Bosnia and Herzegovina',
  BI: 'Brunei',
  BF: 'Burkina Faso',
  BA: 'Burma',
  BY: 'Burundi',
  CA: 'CANADA',
  CL: 'CHILE',
  CN: 'CHINA',
  CO: 'COLOMBIA',
  CU: 'CUBA',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CR: 'Central African Republic',
  CC: 'Congo, Republic of the',
  CD: 'Congo,Democratic Republic of the',
  CS: 'Costa Rica',
  CT: "Cote d'Iviore",
  HR: 'Croatia',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DK: 'DENMARK',
  DM: 'DOMINICA',
  KP: 'DPROK',
  DR: 'Dominican Republic',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  EQ: 'Equatorial Guniea',
  ET: 'Estonia',
  EP: 'Ethiopia',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  DE: 'GERMANY',
  GA: 'Gabon',
  GO: 'Georgia',
  GH: 'Ghana',
  GR: 'Greece',
  GN: 'Grenada',
  GT: 'Guatemala',
  HT: 'Haiti',
  HD: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran',
  IQ: 'Iraq',
  IE: 'Ireland',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JD: 'Jordan',
  KR: 'KOREA',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KO: 'Kosovo',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: 'Laos',
  LV: 'Latvia',
  LB: 'Lebanon',
  LR: 'Liberia',
  LY: 'Libya',
  LT: 'Liechtenstein',
  LN: 'Lithuania',
  LX: 'Luxembourg',
  MO: 'Macau',
  MN: 'Macedonia',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MD: 'Maldives',
  MI: 'Mali',
  ML: 'Malta',
  MS: 'Marshall Island',
  MT: 'Mauritania',
  MU: 'Mauritius',
  MX: 'Mexico',
  MC: 'Monaco',
  MV: 'Mongolia',
  ME: 'Montenegro',
  MA: 'Morocco',
  MZ: 'Mozambique',
  NL: 'NETHERLANDS',
  NB: 'Namibia',
  NP: 'Nepal',
  NZ: 'NewZealand',
  NI: 'Nicaragua',
  NG: 'Nigeria',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PU: 'Palau',
  PS: 'Palestinian Territories',
  PA: 'Panama',
  PP: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines',
  PL: 'Poland',
  PT: 'Portugal',
  QT: 'Qatar',
  RO: 'Romania',
  RU: 'Russia',
  RW: 'Rwanda',
  CH: 'SWITZERLAND',
  SX: 'Saint Kitts and Nevis',
  SL: 'Saint Lucia',
  ST: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  SB: 'Serbia',
  SC: 'Seychelles',
  SF: 'Sierra Leone',
  SG: 'Singapore',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SO: 'Somalia',
  ZA: 'South Africa',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'SriLanka',
  SD: 'Sudan',
  SW: 'Swaziland',
  SE: 'Sweden',
  SY: 'Syria',
  TW: 'TAIWAN',
  TJ: 'Tajikistan',
  TZ: 'Tanzania',
  TH: 'Thailand',
  TG: 'Togo',
  TA: 'Tonga',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates',
  GB: 'United Kingdom',
  US: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VE: 'Venezuela',
  VN: 'Vietnam',
  YE: 'Yemen',
  YU: 'Yugoslavia',
  ZR: 'Zaire',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  ZZ: 'etc.',
};

export const countriesOptions = Object.entries(COUNTRIES).map(
  ([key, value]) => ({ key, value })
);
