export const ROOT_ID =
  'chrome-extension-boilerplate-react-vite-content-view-root';

export const trainStations = [
  'Seoul',
  'Yongsan',
  'Yeongdeungpo',
  'Gwangmyeong',
  'Suwon',
  'Pyeongtaek',
  'CheonanAsan',
  'Cheonan',
  'Jochiwon',
  'Daejeon',
  'Seodaejeon',
  'Gimcheon',
  'Gumi',
  'Gimcheon Gumi',
  'Daegu',
  'Dongdaegu',
  'Pohang',
  'Miryang',
  'Gupo',
  'Busan',
  'Singyeongju',
  'Taehwagang',
  'Ulsan',
  'Haman',
  'Osong',
  'Masan',
  'ChangwonJungang',
  'Gyeongsan',
  'Nonsan',
  'Iksan',
  'Jeongeup',
  'Gwangju-Songjeong',
  'Mokpo',
  'Jeonju',
  'Suncheon',
  'Yeosu-Expo',
  'Daecheon',
  'Cheongnyangni',
  'Jecheon',
  'Donghae',
  'Gangneung',
  'Haengsin',
  'Chuncheon',
  'Namchuncheon',
  'Bujeon',
  'Sintanjin',
  'Yeongdong',
  'Waegwan',
  'Wonju',
  'Jeongdongjin',
  'Hongseong',
];

export const trainStationsOptions = trainStations.map((station) => ({
  key: station,
  value: station,
}));
